name = "FiniteLineSource"
uuid = "64cfb1b1-06f0-48af-b80e-43c410dfe9e8"
authors = ["Marc Basquens <marc5@kth.se> and contributors"]
version = "1.0.0-DEV"

[deps]
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
QuadGK = "~2.9"
SpecialFunctions = "~2.3"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Aqua"]
