name: Run benchmarks

on:
  pull_request:

jobs:
  Benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1.10'
      - uses: julia-actions/julia-buildpkg@latest
      - name: Setup benchmark environment
        run: |
          julia --project=benchmark -e 'using Pkg; Pkg.develop(path = "../FiniteLineSource"); Pkg.add(name="PkgBenchmark"); Pkg.add(name="BenchmarkCI", version="0.1.9"); Pkg.instantiate(); Pkg.resolve(); Pkg.precompile();'
      - name: Run benchmarks
        run: julia -e 'using BenchmarkCI; BenchmarkCI.judge()'
      - name: Post results
        run: julia -e 'using BenchmarkCI; BenchmarkCI.postjudge()'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



#- name: Instantiate and resolve dependencies
#  run: julia --project=FiniteLineSource -e 'using Pkg; Pkg.instantiate(); Pkg.resolve(); Pkg.precompile()'
#- name: Install dependencies
#  run: julia -e 'using Pkg; pkg"add PkgBenchmark BenchmarkCI@0.1.9"'
    